library(tidyverse)


folder <- "../7-Data - 190183 NISAR/oda/20191112/"

degreesODA<-function(degstr){
  n <- regexpr(",",degstr)[1]
  deg<-as.numeric(substr(degstr,n-4,n-3))
  min<-as.numeric(gsub(",",".",substr(degstr,n-2,99)))
  deg <- deg + (min/60)
  return(deg)
}

## 
# files generated by manual dowload from https://odaforalle.au.dk 
# Date 12-11-2019

#bundfauna_artsliste.csv
#fytoplankton.csv
#vegetation_arter.csv
#zooplankton.csv

# -------------- Bottom vegetation -------------- 
dfVeg <- read.table(file=paste0(folder,"vegetation_arter.csv"),sep=";",header=T,stringsAsFactors=F)

dfVeg <- dfVeg %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(StartDato),format = "%Y%m%d")) %>%
  mutate(Lat=degreesODA(Bredde.grad),Lon=degreesODA(Længde.grad)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfVegDistinct <- dfVeg %>%
  group_by(Species) %>%
  summarise() %>%
  ungroup() %>%
  mutate(Table="Bottom Vegetation")

# -------------- Bottom fauna -------------- 
dfFauna <- read.table(file=paste0(folder,"bundfauna_artsliste.csv"),sep=";",header=T,stringsAsFactors=F)

dfFauna <- dfFauna %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Phylum=Artsrække,Species=Artsnavn,Lat,Lon,Date)

dfFaunaDistinct <- dfFauna %>%
  group_by(Phylum,Species) %>%
  summarise() %>%
  ungroup() %>%
  mutate(Table="Bottom Fauna")


# -------------- Phytoplankton -------------- 
dfPhyto <- read.table(file=paste0(folder,"fytoplankton.csv"),sep=";",header=T,stringsAsFactors=F)
dfPhyto <- dfPhyto %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfPhytoDistinct <- dfPhyto %>%
  group_by(Species) %>%
  summarise() %>%
  ungroup() %>%
  mutate(Table="Phytoplankton")


# -------------- Zooplankton -------------- 
dfZoo <- read.table(file=paste0(folder,"zooplankton.csv"),sep=";",header=T,stringsAsFactors=F)
dfZoo <- dfZoo %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfZooDistinct <- dfZoo %>%
  group_by(Species) %>%
  summarise() %>%
  ungroup() %>%
  mutate(Table="Zooplankton")

# -------------- Summary -------------- 




