library(tidyverse)


folder <- "../7-Data - 190183 NISAR/oda/20191112/"

degreesODA<-function(degstr){
  n <- regexpr(",",degstr)[1]
  deg<-as.numeric(substr(degstr,n-4,n-3))
  min<-as.numeric(gsub(",",".",substr(degstr,n-2,99)))
  deg <- deg + (min/60)
  return(deg)
}

## 
# files generated by manual dowload from https://odaforalle.au.dk 
# Date 12-11-2019

#bundfauna_artsliste.csv
#fytoplankton.csv
#vegetation_arter.csv
#zooplankton.csv

# -------------- Bottom vegetation -------------- 
dfVeg <- read.table(file=paste0(folder,"vegetation_arter.csv"),sep=";",header=T,stringsAsFactors=F)

dfVeg <- dfVeg %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(StartDato),format = "%Y%m%d")) %>%
  mutate(Lat=degreesODA(Bredde.grad),Lon=degreesODA(Længde.grad)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfVegDistinct <- dfVeg %>%
  group_by(Species) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  mutate(Table="Bottom Vegetation")

# -------------- Bottom fauna -------------- 
dfFauna <- read.table(file=paste0(folder,"bundfauna_artsliste.csv"),sep=";",header=T,stringsAsFactors=F)

dfFauna <- dfFauna %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Phylum=Artsrække,Species=Artsnavn,Lat,Lon,Date)

dfFaunaDistinct <- dfFauna %>%
  group_by(Phylum,Species) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  mutate(Table="Bottom Fauna")


# -------------- Phytoplankton -------------- 
dfPhyto <- read.table(file=paste0(folder,"fytoplankton.csv"),sep=";",header=T,stringsAsFactors=F)
dfPhyto <- dfPhyto %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfPhytoDistinct <- dfPhyto %>%
  group_by(Species) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  mutate(Table="Phytoplankton")


# -------------- Zooplankton -------------- 
dfZoo <- read.table(file=paste0(folder,"zooplankton.csv"),sep=";",header=T,stringsAsFactors=F)
dfZoo <- dfZoo %>% 
  filter(Kvalitet=="GODK") %>%
  mutate(Date=as.Date(as.character(Dato),format = "%Y-%m-%d")) %>%
  mutate(Lat=degreesODA(ObsSted_bredde),Lon=degreesODA(ObsSted_længde)) %>%
  select(Species=Artsnavn,Lat,Lon,Date)

dfZooDistinct <- dfZoo %>%
  group_by(Species) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  mutate(Table="Zooplankton")

# -------------- STOQ -------------- 

"STOQ_Artsfund_fytoplankton.xlsx"


# -------------- Summary -------------- 

SplitAlternativeSpecies<-function(df){
  # where species name in a record is given with "/" separating two possible alternatives
  # then split to give two records
  # 
  dfsplit <- df %>%
    mutate(Species=gsub(" \\/ ","\\/",Species),
           Species=gsub("\\/ ","\\/",Species),
           Species=gsub(" \\/","\\/",Species)) %>%
    mutate(n1=str_locate_all(Species,"\\/"),n2=str_locate_all(Species," ")) %>%
    mutate(n1=sapply(n1,function(x) unlist(x)[1]),
           n3=sapply(n2,function(x) unlist(x)[2]),
           n2=sapply(n2,function(x) unlist(x)[1])) %>%
    mutate(n2=ifelse(is.na(n2),nchar(Species)+1,n2),
           n3=ifelse(is.na(n3),n2,n3))
  
  
  dfsplit <- dfsplit %>% 
    filter(!is.na(n1)) 
  
  dfsplit <- dfsplit %>%
    mutate(s1=ifelse(n2==n3,
                     ifelse(n1<n2,
                            paste0(substr(Species,1,n1-1)," ",substr(Species,n2,nchar(Species))),
                            substr(Species,1,n1-1)),
                     substr(Species,1,n1-1)),
           s2=ifelse(n2==n3,
                     ifelse(n1<n2,
                            substr(Species,n1+1,nchar(Species)),
                            paste0(substr(Species,1,n2-1)," ",substr(Species,n1+1,nchar(Species)))),
                     substr(Species,n1+1,nchar(Species))))
  
  dfsplit <- dfsplit %>%
    select(-c(n1,n2,n3))
  
  dfsplit <- dfsplit %>% 
    gather(key="Column",value="SpeciesNew",c(s1,s2)) %>%
    select(Species,Table,SpeciesNew)
  
  df <- df %>%
    left_join(dfsplit,by=c("Species","Table")) %>%
    mutate(Note=ifelse(is.na(SpeciesNew),NA,paste0("Split ODA entry: '",Species,"'")),
           Species=ifelse(is.na(SpeciesNew),Species,SpeciesNew)) %>%
    select(-SpeciesNew)
  
  return(df)
}


df <- bind_rows(dfVegDistinct,
                dfFaunaDistinct,
                dfPhytoDistinct,
                dfZooDistinct)


df <- SplitAlternativeSpecies(df)


write.table(df,file="output/ODA_distinct_Species.csv",col.names=T,row.names=F,sep=";",na="",fileEncoding="UTF-8")
